spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toy.board?serverTimezone=UTC
    username: root
    password: 147asd!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect